name: autosolve_client
description: Official Flutter Client for the AutoSolve API
version: 0.0.1
homepage: https://docs.aycd.io/docs/autosolve-api

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_amqp:
    git:
      url: "https://github.com/aycdinc/dart_amqp"
  synchronized: ^2.2.0+2
  random_string: ^2.1.0
  eventify: ^0.1.4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
